version: "3.7"

services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py migrate &&
             gunicorn config.wsgi:application -b 0.0.0.0:8080"
    env_file:
      - ./.env