# .circleci/config.yml

version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2004:202107-01

    steps:
      - checkout

      # Install dependencies and create virtual environment
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt install -y sshpass 
      
      # Grab Code Changes from GitHub
      - run:
          name: Grab Code Changes from GitHub
          command: |
            ssh -i /path/to/private/key ${SSH_USERNAME}@${SERVER_IP} 'cd /home/${PROJECT_FOLDER} && git checkout dev && git pull origin dev'

      # Deploy the application
      - run:
          name: Build Docker Image
          command: |
            ssh -i /path/to/private/key ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && python3 -m venv venv"
          
      - run:
          name: Run Docker Container
          command: |
            ssh -i /path/to/private/key ${SSH_USERNAME}@${SERVER_IP} "cd /home/${PROJECT_FOLDER} && sudo docker-compose up"
      
      
     
     
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - setup_db:
      #     filters:
      #       branches:
      #         only:
      #           - production  
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - production  
      #     requires:
      #       - setup_db

      - update_deploy:
          filters:
            branches:
                only:
                  - dev