# Generated by Django 4.1 on 2023-11-10 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='user',
        ),
    ]
