# Generated by Django 4.1 on 2023-11-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_organisations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='logo',
            field=models.ImageField(null=True, upload_to='organisation_logo/'),
        ),
    ]
