# Generated by Django 4.1 on 2023-12-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetfiles',
            name='sha256',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
