# Generated by Django 4.1 on 2023-12-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_datasetfiles_sha256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetfiles',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
