# Generated by Django 4.1 on 2023-12-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_uploaded_by_datasetfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
    ]
