# Generated by Django 4.1 on 2023-12-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_datasetfiles_dataset_alter_datasetfiles_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
