# Generated by Django 4.1 on 2024-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_datasetfiles_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisations',
            name='user',
        ),
        migrations.AddField(
            model_name='organisations',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organisations',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisations',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=250),
        ),
        migrations.AddField(
            model_name='organisations',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisations',
            name='type',
            field=models.CharField(choices=[('cooperate_organisation', 'cooperate_organisation'), ('cooperate_society', 'cooperate_society')], default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='organisations',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
