# Generated by Django 4.1 on 2024-01-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetfiles',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
