# Generated by Django 4.1 on 2024-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_datasets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=250),
        ),
    ]
