# Generated by Django 4.1 on 2024-02-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_datasets_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatasetViews',
        ),
    ]
