# Generated by Django 4.1 on 2024-03-03 02:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CategoryAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=650)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_analysis', to='main.categories')),
            ],
        ),
    ]
